version: '3'

services:
  # PHP(Laravel) - Service
  laravel:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-image
    container_name: example
    restart: unless-stopped
    tty: true
    working_dir: /var/www/
    environment:
      TZ: "America/Belem"
    volumes:
      - ./:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  # NGINX - Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    environment:
      TZ: "America/Belem"
    ports:
      - "80:80"
      - "8143:443"
    volumes:
      - ./:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # Banco de Dados - Service
  db:
    image: mysql:5.7.22
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      TZ: "America/Belem"
    volumes:
      - dbmysql:/var/lib/mysql
      - ./docker-files/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

# Volumes
volumes:
  dbmysql:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge
